### ISSUE TITLE
Failed large batch upload

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#891] opened 2018-02-05 15:35 UTC
I tested a batch of 101 small objects (15 KB each). The files seemed to upload without any problems, but when I clicked "Add files to batch" after they had all uploaded, I was brought to the "We're sorry, but something went wrong," error message. 

When I went back into the system, I could see the batch listed (146) and its status was partially completed. All but one file was uploaded and associated with the batch. However, there was no error message telling me which file was missing.

I was able to publish the 100 objects associated with the batch.

**Comment by mark-dce** [comment] 2018-02-27 22:29
We suspect this has the same root cause as #895.  We're putting the fix in place and would like to re-test this

**Comment by mark-dce** [comment] 2018-02-28 16:49
Confirmed duplicate of #895.  Closing this ticket and will track the issue against the other ticket.

**Closed by mark-dce** 2018-02-28 16:49 UTC
Labels: acceptance testing, backlog, bug, depends on
