### ISSUE TITLE
Batch import doesn't work with multiple files

### ISSUE THREAD

**Issue by val99erie** [curationexperts/epigaea#772] opened 2017-12-14 17:31 UTC
**Steps to reproduce the problem:**

* Edit `docs/all_inputs.xml` and delete the `<tufts:id>` entry from the file.

* Create the sample files that are listed in the `filename` element in `docs/all_inputs.xml`:

```bash
$ touch docs/pdf-sample.pdf
$ touch docs/another-file.txt
```

* Visit `http://localhost:3000/sidekiq/queues` and note the number of jobs that have already been processed so you can figure out if any new jobs get queued during this batch import. 

* In the browser, select "Import Objects" from the nav menu

* When the form loads, upload the `docs/all_inputs.xml` file, and click 'Next

* Click "add additional files to this batch"

* Click "Add Files" and upload the 2 sample files you created in the steps above.

* Click "Add Files to Batch"

**Expected Behavior:**

If you wait a few seconds (long enough for background jobs to run), the batch status will change to 'Complete' and you will see a link for the newly-created record.  If you click the link, you'll see the new record with your 2 files correctly attached to it.

**Actual Behavior:**

If you wait and reload the page, the batch status is still 'Unavailable', and if you visit `http://localhost:3000/sidekiq/queues`, notice that no new jobs have been queued or processed.

**Note:**

If you remove one of the two `filename` entries from `doc/all_inputs.xml`, then the import will work as expected.

**Comment by no-reply** [comment] 2017-12-14 18:23
I just ran through these instructions on http://epigaea.curationexperts.com and got the expected behavior. see: http://epigaea.curationexperts.com/xml_imports/50

**Comment by bess** [comment] 2017-12-14 22:05
I can't reproduce this either. @val99erie Are you still seeing this?

**Comment by val99erie** [comment] 2017-12-14 22:08
@bess Sorry, there was some discussion on slack that didn't get added to this ticket.  Tom realized that the order that the files are uploaded in the UI affects whether or not the error happens.  I think he's working on a solution.

**Comment by bess** [comment] 2017-12-14 22:19
@no-reply I'm re-assigning this to you, since it sounds like you're working on it with more context than I have

**Closed** 2017-12-15 02:48 UTC
Labels: bug, in progress
