### ISSUE TITLE
Create/Edit a metadata Template

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#118] opened 2017-07-21 17:47 UTC
- [ ] I can get to a new empty template
- [ ] a Template must have a name
- [ ] All metadata fields across works are available to be populated
- [ ] If I populate any values, they are persisted in the template when I click "Save"
- [ ] If change any values, they are persisted when I click "Save"
- [ ] The template edit form is very similar to (or ideally almost exactly like) the metadata form for any other repository object.

**Comment by no-reply** [comment] 2017-08-08 15:28
Closing this as a duplicate of #96.

**Closed by no-reply** 2017-08-08 15:28 UTC
Labels: in progress
