### ISSUE TITLE
BATCH INGEST: Batch not being processed

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#788] opened 2017-12-15 21:32 UTC
**ISSUE** 
Margaret Peachy submitted [Batch #104](http://epigaea.curationexperts.com/xml_imports/65) some time ago and the status is listed as "unavailable" and none of the files in her manifest are showing up.

@mpeachy - could you attach your import to this file for us to take a look at?

**Comment by mpeachy** [comment] 2017-12-18 13:45
Looks like xml is not a supported file type in GitHub, so I can't attach the metadata file to the ticket. I will email it to @mark-dce now.

**Comment by mark-dce** [comment] 2017-12-18 15:56
@mpeachy - thanks - I posted it to google drive and folks should be able to grab the sample file here: https://drive.google.com/file/d/1N5WQCGY7_LAbEm6cDnh9LIT5dGOa5_R4/view?usp=sharing

**Comment by no-reply** [comment] 2017-12-19 00:16
@mark-dce I dug into this and it was fixed by #783 ,which is not yet deployed. @mpeachys issue depends on the order multiple files are uploaded. 

I'm closing this as a duplicate of #772

**Closed by no-reply** 2017-12-19 00:16 UTC
Labels: bug, ready
