### ISSUE TITLE
Inability to save edits on object updated by template

### ISSUE THREAD

**Issue by adriennepruitt2** [curationexperts/epigaea#486] opened 2017-10-23 17:09 UTC
If you update an object via template, and the template completes, and then you open the object and attempt to edit it, you cannot save the object. We have gotten two different error message in testing, appended.

**Comment by Alexandermay** [comment] 2017-10-23 17:09
![Screen Shot 2017-10-23 at 1.08.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f06b7191a379f112234f5e575ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df643e64a5da114356ae3732431.png)

I'm adding the first issue we saw.

**Comment by mpeachy** [comment] 2017-10-23 17:11
Here's the second error:
![save draft error](https://user-images.githubusercontent.com/16196574/31902686-b3de356c-b7f3-11e7-99d9-d397a90865f4.JPG)

**Comment by no-reply** [comment] 2017-10-25 21:32
Testing has led us to believe that this is related to the `published` workflow state, rather than templates. We can reproduce by:

  - Creating an item;
  - Publishing the item;
  - Attempt to edit the item (error);
  - Click back to the item show view;
  - Attempt to edit again (success).

**Comment by no-reply** [comment] 2017-10-25 23:52
My current working hypothesis is that this is happening because the `has_draft` property is being updated in the background, causing locking issues.

**Comment by mark-dce** [comment] 2017-11-03 15:23
We believe this has been closed by work completed on other draft tickets.  Mark will attempt to reproduce the issues and close the ticket if unable to reproduce.

**Closed** 2017-11-28 12:51 UTC
Labels: acceptance testing, bug, ready
